lab1:
  cpu: 2
  mem: 4G
  disk: 5G
  image: jammy
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
  build_scripts:
    - ./multipass-orchestrator-configurations/lab-env/build.sh
