mp-v2-ros-bsp:
  cpu: 2
  mem: 2G
  disk: 15G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/mangdangroboticsclub/mini_pupper_ros_bsp.git
  build_scripts:
    - "sed -i '/reboot/d' ./mini_pupper_ros_bsp/setup.sh"
    - "./mini_pupper_ros_bsp/setup.sh v2"
