mp-v2-ros-bsp:
  cpu: 2
  mem: 2G
  disk: 15G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - "-b for_review https://github.com/hdumcke/mini_pupper_ros_bsp.git"
  build_scripts:
    - "./mini_pupper_ros_bsp/setup.sh v2"
