mp-v2-stanford:
  cpu: 2
  mem: 2G
  disk: 3G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/mangdangroboticsclub/mini_pupper.git
  build_scripts:
    - ./mini_pupper/v2_bsp_stanford_web_controller/setup_testing.sh
  run_scripts:
    - ./StanfordQuadruped/tests/run_all_tests.sh
