stm32_dev:
  cpu: 4
  mem: 2G
  disk: 15G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
    - https://github.com/libopencm3/libopencm3.git
    - https://github.com/libopencm3/libopencm3-miniblink.git
  build_scripts:
    - ./multipass-orchestrator-configurations/stm32-dev/build.sh
