network:
    ethernets:
        eth0:
            dhcp4: no
            addresses: [192.168.100.254/24]
            optional: true
    version: 2
    wifis:
        wlan0:
            access-points:
                ssid:
                    password: XXXXX
            dhcp4: true
            optional: true
