dev:
  cpu: 2
  mem: 4G
  disk: 10G
  image: jammy
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
  build_scripts:
    - ./multipass-orchestrator-configurations/TeamCdR2024/build.sh
